id: P001828
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:23:59.578922
source_metadata:
  id: bdr:W3CN5429
  title: ཡ་ཆེན་ཨོ་རྒྱན་བསམ་གཏན་གླིང་གི་བསང་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    c5cb09f26762499391098b41e9b5228f:
      image_group_id: I3CN5431
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
