id: P001828
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5429
  title: ཡ་ཆེན་ཨོ་རྒྱན་བསམ་གཏན་གླིང་གི་བསང་ཡིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    c5cb09f26762499391098b41e9b5228f:
      image_group_id: I3CN5431
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
